theme: jekyll-theme-minimal
title: CANTRIP
description: reCurrent Additive Networks for Temporal RIsk Prediction
show_downloads: true
exclude: 
  - sphinx/Makefile
  - sphinx/make.bat
  - sphinx/source
  - sphinx/html/objects.inv
include:
  - sphinx/html/_modules
  - sphinx/html/_static
